name: flutter_dynamic_widget
description: A Dynamic Widget Runtime from Json to Flutter Widgets based on the json_widget spec.
version: 1.0.1+1
homepage: https://github.com/rodydavis/flutter_dynamic_widget
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  build_runner: ^1.10.0
  shortid: ^0.1.1
  url_launcher: ^5.4.7
  widget_gen: ^1.0.0+5
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_version: ^2.0.0

flutter:
  uses-material-design: true
